name: Publish

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.30/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    - name: Publish test
      run |
        earthly --secret PYPI_TOKEN=${{ secrets.test_pypi_password }} --ci +publish -r testpypi
    - name: Publish
      if: contains(github.ref, 'master')
      run: |
        earthly --secret PYPI_TOKEN=${{ secrets.pypi_password }} --ci +publish
